# SOPS configuration
# Defines which keys can decrypt secrets

creation_rules:
  - path_regex: nixos/machines/neptune/secrets\.yaml$
    key_groups:
      - age:
          # tpx1
          - age1zqy69csk5kgyuu46xmhdvedksfh4qr6msc670ut8mynsktcv2gcqqujp2h
          # neptune
          - age1j3lrczvct4yhd8gzg7rnwxmf3tqfgmhvut40czlxua8qxy2hh38q97ueve

  - path_regex: nixos/users/.*/secrets\.yaml$
    key_groups:
      - age:
          # tpx1
          - age1zqy69csk5kgyuu46xmhdvedksfh4qr6msc670ut8mynsktcv2gcqqujp2h