paths:
  camera001:
    source: "${SC_CAMERA001_RTSP_URL}"
    sourceOnDemand: yes
    sourceOnDemandCloseAfter: 5s
  camera002:
    source: "${SC_CAMERA002_RTSP_URL}"
    sourceOnDemand: yes
    sourceOnDemandCloseAfter: 5s
  security:
    runOnDemand: >
      ffmpeg -loglevel error 
      -rtsp_transport tcp -i "${SC_CAMERA001_RTSP_URL}"
      -rtsp_transport tcp -i "${SC_CAMERA002_RTSP_URL}"
      -filter_complex "[0:v][1:v]hstack=inputs=2[v]" -map "[v]"
      -c:v libx264 -preset ultrafast -f rtsp
      rtsp://localhost:$RTSP_PORT/security
    runOnDemandRestart: yes
    runOnDemandCloseAfter: 5s
    source: rtsp://localhost:${RTSP_PORT}/security
    readUser: "${SC_USERNAME}"
    readPass: "${SC_PASSWORD}"
