authMethod: internal
authInternalUsers:
  - user: "NULL"
    pass: "NULL"
    permissions:
      - action: read
paths:
  nosignal:
    runOnDemand: >
      ffmpeg -f lavfi -re -i color=size=1280x720:rate=30:color=black
             -vf "drawtext=text='NO SIGNAL':fontcolor=white:fontsize=60:
                  x=(w-text_w)/2:y=(h-text_h)/2"
             -c:v libx264 -preset ultrafast -tune stillimage -f rtsp
             rtsp://127.0.0.1:$RTSP_PORT/nosignal
    runOnDemandRestart: yes
    sourceOnDemandCloseAfter: 5s
  camera001:
    source: "NULL"
    sourceOnDemand: yes
    sourceOnDemandCloseAfter: 5s
    fallback: rtsp://127.0.0.1:$RTSP_PORT/nosignal
  camera002:
    source: "NULL"
    sourceOnDemand: yes
    sourceOnDemandCloseAfter: 5s
    fallback: rtsp://127.0.0.1:$RTSP_PORT/nosignal
  security:
    runOnDemand: >
      ffmpeg -loglevel error
            -rtsp_transport tcp -i rtsp://127.0.0.1:$RTSP_PORT/camera001
            -rtsp_transport tcp -i rtsp://127.0.0.1:$RTSP_PORT/camera002
            -filter_complex "[0:v][1:v]hstack=inputs=2[v]" -map "[v]"
            -c:v libx264 -preset ultrafast -f rtsp
            rtsp://127.0.0.1:$RTSP_PORT/$MTX_PATH
    runOnDemandRestart: yes
    runOnDemandCloseAfter: 5s
    source: rtsp://127.0.0.1:$RTSP_PORT/security
