authMethod: internal
authInternalUsers:
  - user: "NULL"
    pass: "NULL"
    permissions:
      - action: read
paths:
  nosignal:
    runOnDemand: >
      ffmpeg -f lavfi -re -i color=size=1280x720:rate=30:color=black
             -vf "drawtext=text='NO SIGNAL':fontcolor=white:fontsize=60:
                  x=(w-text_w)/2:y=(h-text_h)/2"
             -c:v libx264 -preset ultrafast -tune stillimage -f rtsp
             rtsp://127.0.0.1:8554/nosignal
    runOnDemandRestart: yes
    sourceOnDemandCloseAfter: 20s
    source: publisher
  camera001:
    source: "rtsp://placeholder"
    sourceOnDemand: yes
    sourceOnDemandStartTimeout: 10s
    sourceOnDemandCloseAfter: 20s
    fallback: /nosignal
  camera002:
    source: "rtsp://placeholder"
    sourceOnDemand: yes
    sourceOnDemandStartTimeout: 10s
    sourceOnDemandCloseAfter: 20s
    fallback: /nosignal
  security:
    runOnDemand: >
      ffmpeg -loglevel error -reconnect 1 -reconnect_at_eof 1 -reconnect_streamed 1 -reconnect_delay_max 2
            -rtsp_transport tcp -i rtsp://${MTX_AUTHINTERNALUSERS_0_USER}:${MTX_AUTHINTERNALUSERS_0_PASS}@127.0.0.1:8554/camera001
            -rtsp_transport tcp -i rtsp://${MTX_AUTHINTERNALUSERS_0_USER}:${MTX_AUTHINTERNALUSERS_0_PASS}@127.0.0.1:8554/camera002
            -filter_complex "[0:v][1:v]hstack=inputs=2[v]" -map "[v]"
            -c:v libx264 -preset ultrafast -f rtsp
            rtsp://127.0.0.1:8554/security
    runOnDemandRestart: yes
    runOnDemandStartTimeout: 15s
    runOnDemandCloseAfter: 25s
    source: publisher
