logLevel: debug
authMethod: internal
authInternalUsers:
  - user: "${MTX_ADMIN_USERNAME}"
    pass: "${MTX_ADMIN_PASSWORD}"
    permissions:
      - action: read
      - action: publish
      - action: api

  - user: "${MTX_VIEWER001_USERNAME}"
    pass: "${MTX_VIEWER001_PASSWORD}"
    permissions:
      - action: read
  
  - user: test
    pass: test
    permissions:
      - action: read

  # Localhost (container)
  - user: any
    pass:
    ips: ["127.0.0.1", "::1"]
    permissions:
      - action: read
      - action: publish

paths:
  camera001:
    runOnDemand: |
      /bin/sh -c '
      while true; do
        if ffprobe -v quiet -print_format json -show_streams "${SC_CAMERA001_RTSP_URL}" > /dev/null 2>&1; then
          ffmpeg -loglevel error -hide_banner -rtsp_transport tcp -i "${SC_CAMERA001_RTSP_URL}" -c copy -f rtsp rtsp://127.0.0.1:8554/camera001
        else
          /scripts/ffmpeg/no_signal.sh rtsp "Camera-001"
        fi
        sleep 5
      done
      '
    runOnDemandRestart: yes
    runOnDemandStartTimeout: 15s
    runOnDemandCloseAfter: 15s
    source: publisher

  camera002:
    runOnDemand: |
      /bin/sh -c '
      while true; do
        if ffprobe -v quiet -print_format json -show_streams "${SC_CAMERA002_RTSP_URL}" > /dev/null 2>&1; then
          ffmpeg -loglevel error -hide_banner -rtsp_transport tcp -i "${SC_CAMERA002_RTSP_URL}" -c copy -f rtsp rtsp://127.0.0.1:8554/camera002
        else
          /scripts/ffmpeg/no_signal.sh rtsp "Camera-002"
        fi
        sleep 5
      done
      '
    runOnDemandRestart: yes
    runOnDemandStartTimeout: 15s
    runOnDemandCloseAfter: 15s
    source: publisher

  # security:
  #   runOnDemand: >
  #     ffmpeg -loglevel error -timeout 10000000
  #           -rtsp_transport tcp -i rtsp://127.0.0.1:8554/camera001
  #           -rtsp_transport tcp -i rtsp://127.0.0.1:8554/camera002
  #           -filter_complex "[0:v][1:v]hstack=inputs=2[v]" -map "[v]"
  #           -c:v libx264 -preset ultrafast -f rtsp
  #           rtsp://127.0.0.1:8554/security
  #   runOnDemandRestart: yes
  #   runOnDemandStartTimeout: 15s
  #   runOnDemandCloseAfter: 25s
  #   source: publisher
