logLevel: debug
authMethod: internal
authInternalUsers:
  - user: "${MTX_ADMIN_USERNAME}"
    pass: "${MTX_ADMIN_PASSWORD}"
    permissions:
      - action: read
      - action: publish
      - action: api

  - user: "${MTX_VIEWER001_USERNAME}"
    pass: "${MTX_VIEWER001_PASSWORD}"
    permissions:
      - action: read
  
  - user: test
    pass: test
    permissions:
      - action: read

  # Localhost (container)
  - user: any
    pass:
    ips: ["127.0.0.1", "::1"]
    permissions:
      - action: read
      - action: publish

paths:
  nosignal_camera001:
    source: publisher
    runOnDemand: /scripts/ffmpeg/no_signal.sh camera001 rtsp://127.0.0.1:8554/nosignal_camera001
    runOnDemandRestart: yes
    sourceOnDemandCloseAfter: 10s
  nosignal_camera002:
    source: publisher
    runOnDemand: /scripts/ffmpeg/no_signal.sh camera002 rtsp://127.0.0.1:8554/nosignal_camera002
    runOnDemandRestart: yes
    sourceOnDemandCloseAfter: 10s
  camera001:
    source: "${SC_CAMERA001_RTSP_URL}"
    sourceOnDemand: yes
    sourceOnDemandStartTimeout: 10s
    sourceOnDemandCloseAfter: 20s
    fallback: /nosignal_camera001
  camera002:
    source: "${SC_CAMERA002_RTSP_URL}"
    sourceOnDemand: yes
    sourceOnDemandStartTimeout: 10s
    sourceOnDemandCloseAfter: 20s
    fallback: /nosignal_camera002
  security:
    runOnDemand: >
      ffmpeg -loglevel error -timeout 10000000
            -rtsp_transport tcp -i rtsp://127.0.0.1:8554/camera001
            -rtsp_transport tcp -i rtsp://127.0.0.1:8554/camera002
            -filter_complex "[0:v][1:v]hstack=inputs=2[v]" -map "[v]"
            -c:v libx264 -preset ultrafast -f rtsp
            rtsp://127.0.0.1:8554/security
    runOnDemandRestart: yes
    runOnDemandStartTimeout: 15s
    runOnDemandCloseAfter: 25s
    source: publisher
