# Machine-specific secrets for neptune
# This file is auto-generated from secrets.yaml
# Placeholder values for flake check - real values generated by sync-secrets script

{
  # Tailscale auth key
  services.tailscale.authKey = "REPLACE_WITH_REAL_VALUE";

  # SSH authorized keys for morgan user
  users.users.morgan.openssh.authorizedKeys.keys = [
    "REPLACE_WITH_REAL_KEY"
  ];
}
