# Programmatic Nix expression for syncing secrets
# This parses secrets.yaml, processes it in Nix, and generates encrypted SOPS files
#
# Usage: nix run .#sync-secrets

{ pkgs ? import <nixpkgs> { }
, lib ? pkgs.lib
, secretsFile ? ../../secrets.yaml
}:

let
  # Parse YAML to Nix by converting YAML -> JSON -> Nix
  parseYaml = file:
    builtins.fromJSON (
      builtins.readFile (
        pkgs.runCommand "yaml-to-json" { nativeBuildInputs = [ pkgs.yq ]; } ''
          ${pkgs.yq}/bin/yq eval -o json "${file}" > $out
        ''
      )
    );
  
  # Read and parse secrets
  secrets = parseYaml secretsFile;
  
  # Extract nested values with proper error handling
  getNested = path: default: obj:
    let
      parts = lib.splitString "." path;
      go = key: rest: value:
        if rest == [] then value
        else if value ? ${lib.head rest} then go (lib.head rest) (lib.tail rest) value.${lib.head rest}
        else default;
    in
      go "" parts obj;
  
  # Hash password function (pure Nix)
  hashPassword = password:
    lib.removeSuffix "\n" (
      builtins.readFile (
        pkgs.runCommand "hash-password" { nativeBuildInputs = [ pkgs.mkpasswd ]; } ''
          echo -n "${password}" | ${pkgs.mkpasswd}/bin/mkpasswd -m sha-512 -s > $out
        ''
      )
    );
  
  # Generate YAML content from Nix values
  toYaml = value:
    if lib.isString value then value
    else if lib.isInt value || lib.isBool value then toString value
    else if lib.isList value then
      lib.concatMapStringsSep "\n" (v: "  - ${toYaml v}") value
    else if lib.isAttrs value then
      lib.concatStringsSep "\n" (
        lib.mapAttrsToList (name: val: "${name}: ${if lib.isList val then "\n${toYaml val}" else toYaml val}") value
      )
    else toString value;
  
  # Extract secrets programmatically
  neptuneSecrets = {
    tailscale_auth_key = secrets.nixos.machines.neptune.tailscale.auth_key;
    ssh_authorized_keys = secrets.nixos.machines.neptune.ssh.authorized_keys;
  };
  
  morganSecrets = {
    morgan_password_hash = hashPassword secrets.nixos.users.morgan.password;
    adguard_username = secrets.nixos.users.morgan.adguard.username;
    adguard_password_hash = secrets.nixos.users.morgan.adguard.password; # Could hash this too
  };
  
  # Generate YAML strings
  neptuneYaml = ''
    tailscale_auth_key: ${neptuneSecrets.tailscale_auth_key}
    ssh_authorized_keys:
    ${lib.concatMapStringsSep "\n" (key: "  - ${key}") neptuneSecrets.ssh_authorized_keys}
  '';
  
  morganYaml = ''
    morgan_password_hash: ${morganSecrets.morgan_password_hash}
    adguard_username: ${morganSecrets.adguard_username}
    adguard_password_hash: ${morganSecrets.adguard_password_hash}
  '';
  
  # Script that uses the Nix-generated YAML and encrypts with sops
  syncScript = pkgs.writeShellApplication {
    name = "sync-secrets";
    runtimeInputs = [ pkgs.sops ];
    text = ''
      set -euo pipefail
      
      REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
      cd "$REPO_ROOT"
      
      # Helper to encrypt YAML content
      encrypt_yaml() {
        local output="$1"
        local content="$2"
        local tmp=$(mktemp)
        echo -n "$content" > "$tmp"
        
        if sops -e "$tmp" > "$output" 2>/dev/null; then
          echo "  ✓ Encrypted: $output"
        else
          cp "$tmp" "$output"
          echo "  ⚠ Created unencrypted: $output (run: sops $output)"
        fi
        rm "$tmp"
      }
      
      echo "Syncing secrets (YAML parsed and processed in Nix)..."
      
      # Use the YAML generated by Nix
      encrypt_yaml "nixos/machines/neptune/secrets.yaml" "${neptuneYaml}"
      encrypt_yaml "nixos/users/morgan/secrets.yaml" "${morganYaml}"
      
      echo ""
      echo "✓ Secrets synced successfully!"
    '';
  };
  
in
{
  # The actual script
  sync-secrets = syncScript;
  
  # Expose the parsed secrets for inspection/debugging
  secrets = secrets;
  neptuneSecrets = neptuneSecrets;
  morganSecrets = morganSecrets;
  
  # Expose the generated YAML (for debugging)
  neptuneYaml = neptuneYaml;
  morganYaml = morganYaml;
}
