# User-specific secrets for morgan
# This file is auto-generated from secrets.yaml
# Placeholder values for flake check - real values generated by sync-secrets script

{
  # User password hash (generated from plaintext password)
  users.users.morgan.hashedPassword = "REPLACE_WITH_REAL_HASH";

  # AdGuard Home admin user
  services.adguardhome.settings.users = [
    {
      name = "REPLACE_WITH_REAL_USERNAME";
      password = "REPLACE_WITH_REAL_PASSWORD";
    }
  ];
}
